Optimise the deployment process

diff --git a/Deployment/ProductionStageDeployment/Deployment/Jenkinsfile b/Deployment/ProductionStageDeployment/Deployment/Jenkinsfile
--- a/Deployment/ProductionStageDeployment/Deployment/Jenkinsfile
+++ b/Deployment/ProductionStageDeployment/Deployment/Jenkinsfile
@@ -3,8 +3,6 @@ pipeline {
 
     environment {
         AWS_SSH_KEY = credentials('AWS_CREDS')  // Use the AWS PEM file for SSH access
-        PROJECT_DIR = 'teamatramshedtech'
-        GIT_CREDS = credentials('NITHIN_GIT_CREDS')
     }
 
     stages {
@@ -29,67 +27,32 @@ pipeline {
             }
         }
 
-        stage('Clone Project to AWS Instance') {
+        stage('Build Project') {
             steps {
                 script {
-                    if (env.INSTANCE_IP) {
-                        def encodedUsername = URLEncoder.encode(GIT_CREDS_USR, "UTF-8")
-                        def encodedPassword = URLEncoder.encode(GIT_CREDS_PSW, "UTF-8")
-
-                        // Clone the repository to the instance
-                        sh """
-ssh -i $AWS_SSH_KEY -o StrictHostKeyChecking=no ec2-user@${INSTANCE_IP} << EOF
-# Remove existing directory if it exists
-if [ -d "${PROJECT_DIR}" ]; then
-    rm -rf ${PROJECT_DIR}
-fi
-
-# Clone the repository
-git clone https://${encodedUsername}:${encodedPassword}@git.cardiff.ac.uk/c23051986/teamatramshedtech.git
-
-# Navigate to the repository directory
-cd ${PROJECT_DIR}
-
-# Checkout to the specific branch
-git checkout 82_Deploy_project_to_production_environment
-EOF
-"""
-                        sleep 30
-                        sh 'echo "Project cloned to the AWS instance."'
-                    } else {
-                        error "Instance IP is not available."
-                    }
-                }
-            }
-        }
-
-        stage('Build Project on AWS Instance') {
-            steps {
-                script {
-                    if (env.INSTANCE_IP) {
-                        timeout(time: 10, unit: 'MINUTES') {
-                            // Build commands on the AWS instance
-                            sh """
-ssh -i $AWS_SSH_KEY -o StrictHostKeyChecking=no ec2-user@${INSTANCE_IP} << EOF
-# Fail the script on any error
-set -e
-cd ${PROJECT_DIR}
-chmod +x gradlew
-
-# Run the Gradle build and redirect output to a log file
-./gradlew clean build --no-daemon  >> gradle_build.log 2>&1
-
-# Check if the build was successful by looking for the JAR file
-if [ ! -f build/libs/eventmanagement-0.0.1-SNAPSHOT.jar ]; then
-    echo "Build failed. JAR file not found." >> gradle_build.log 2>&1
-    exit 1
-fi
-EOF
-"""
-                            sh 'echo "Project built on the AWS instance."'
+                    dir("${WORKSPACE}") {
+                        if (env.INSTANCE_IP) {
+                            timeout(time: 10, unit: 'MINUTES') {
+                                // Build commands on the AWS instance
+                                sh '''
+                                    # Fail the script on any error
+                                    set -e
+                                    chmod +x gradlew
+                                    
+                                    # Run the Gradle build and redirect output to a log file
+                                    ./gradlew clean build --no-daemon  >> gradle_build.log 2>&1
+                                    
+                                    # Check if the build was successful by looking for the JAR file
+                                    if [ ! -f build/libs/eventmanagement-0.0.1-SNAPSHOT.jar ]; then
+                                        echo "Build failed. JAR file not found." >> gradle_build.log 2>&1
+                                        exit 1
+                                    fi
+                                    '''
+                                sh 'echo "Project built completed."'
+                            }
+                        } else {
+                            error "Instance IP is not available."
                         }
-                    } else {
-                        error "Instance IP is not available."
                     }
                 }
             }
@@ -98,20 +61,23 @@ EOF
         stage('Run Project on AWS Instance') {
             steps {
                 script {
-                    if (env.INSTANCE_IP) {
-                        // Run project on the AWS instance in the background
-                        sh """
+                    dir("${WORKSPACE}") {
+                        if (env.INSTANCE_IP) {
+                            // Run project on the AWS instance in the background
+                            sh """
+scp -i $AWS_SSH_KEY -o StrictHostKeyChecking=no build/libs/eventmanagement-0.0.1-SNAPSHOT.jar ec2-user@${INSTANCE_IP}:~ 
 ssh -i $AWS_SSH_KEY -o StrictHostKeyChecking=no ec2-user@${INSTANCE_IP} << EOF
 # Fail the script on any error
 set -e
-cd ${PROJECT_DIR}
-nohup java -jar build/libs/eventmanagement-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
+
+nohup java -jar eventmanagement-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
 echo \$! > app.pid
 EOF
 """
-                        sh 'echo "Application started in the background on the AWS instance."'
-                    } else {
-                        error "Instance IP is not available."
+                            sh 'echo "Application started in the background on the AWS instance."'
+                        } else {
+                            error "Instance IP is not available."
+                        }
                     }
                 }
             }
